### PR TITLE
Use flexbox and relative viewport to center .application

### PR DESCRIPTION
**Pull request by pavsaund**
## Summary

- Fix centring of the .application container div, so it works on more screen and allows users to select their provider on mobile devices

### Fixed

- Fix centring of the .application container div, so it works on more screen and allows users to select their provider on mobile devices

### CODE REVIEW

**Comment by pavsaund** [comment]
@jakhog I didn't know how to simulate the actual content to verify how that looks, but I manually added the same div's as on the deployed version and it looked similar enough. My main goal here was to allow users to be able to select providers or tenants on mobile devices.

**Comment by jakhog** [comment]
@pavsaund that's a good point. I think we maybe should add a full-backend mock (if it's not too much hassle) to enable working on the frontend alone. The setup for the whole thing is quite involved locally if all you want to do is fix the frontend.

**Comment by jakhog** [comment]
I will test this out locally to confirm it works and see what I can do quickly with a backend mock later.

**Comment by pavsaund** [comment]
Awesome! Ping me if I need to do something!

**Review by jakhog — CHANGES_REQUESTED** [review]
The flexbox thingy adds a (slightly annoying) scrollbar to the page. Is there any way we could get rid of it? I tried a few quick things, but css and especially flexible boxes aren't my speciality so I couldn't make it work.

I've made a backend-mock thing in a PR here: https://github.com/dolittle-platform/Authentication/pull/18
So if you want to test it out yourself locally, you could just pick out the stuff from `Deployment/Frontend` until it is approved and merged.

**Comment by jakhog** [comment]
By the way - are you not allowed to create branches and code directly on this repository? I just now saw that you had been working on your own fork...

**Comment by pavsaund** [comment]
Hmm, I also encountered the scroll-bar issue, but thought I had fixed it. I'll dive back in.
Regarding contributing - no, I don't have write access. But Forking works fine too :)

**Comment by pavsaund** [comment]
@jakhog: The `Deployment/Frontend` worked great! Could you take a look and verify that there no longer is a scroll bar?

**Review by jakhog — APPROVED** [review]
I can confirm it is looking mighty fine 👍

**Pull request merged**
